version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
        POSTGRES_PASSWORD: 'testtest'
    volumes:
        - pgdata:/var/lib/postgresql/data
        - /dev/shm
    ports:
        - "127.0.0.1:5432:5432"
volumes:
  pgdata:
  