version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
        POSTGRES_PASSWORD: 'testtest'
    volumes:
        - pgdata:/var/lib/postgresql/data
        - /dev/shm
    ports:
        - "5432:5432"
  web:
    build: .
    volumes:
      - .:/movies_service
    environment:
      PORT: "8080"
      DATABASE_URL: "postgres://postgres:testtest@postgres/postgres"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
volumes:
  pgdata:
  
