# Generated by Django 2.2.5 on 2019-09-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='movies',
            field=models.ManyToManyField(related_name='directors', to='movie.Movie'),
        ),
    ]
